package constant;

public class ConnectionLocator {
    public static final String CSS_VALIDATE = "android.widget.TextView[text=\"Validate\"]";
    public static final String CSS_ADD_SUCCESS = "android.widget.TextView[text=\"This bank account has\nbeen added to your\nConnections.\"]";
    public static final String ADD_SUCCESS = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.TextView";
    public static final String CSS_BANK_LOCATION_TITLE = "android.widget.TextView[text=\"Bank location\"]";
    public static final String ADD_CONNECTION_BUTTON = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup";
    public static final String CSS_TYPE_YOUR_LOCAL_BANK = "android.widget.TextView[text=\"Your local bank account\"]";
    public static final String CSS_TYPE_OTHER_LOCAL_BANK = "android.widget.TextView[text=\"Other local bank account\"]";
    public static final String CSS_TYPE_OVERSEAS_BANK = "android.widget.TextView[text=\"Overseas bank account\"]";
    public static final String CSS_TYPE_OVERSEAS_CASH_PAYOUT = "android.widget.TextView[text=\"Overseas cash payout\"]";
    public static final String CSS_TYPE_OVERSEAS_MOBILE_MONEY = "android.widget.TextView[text=\"Overseas mobile money\"]";
    public static final String CSS_ACC_FIRST_NAME = "android.widget.EditText[text=\"Account holder first name\"]";
    public static final String CSS_ACC_LAST_NAME = "android.widget.EditText[text=\"Account holder last name\"]";
    public static final String CSS_ACC_EMAIL = "android.widget.EditText[text=\"Account holder's email (optional)\"]";
    public static final String CSS_ACC_NUMBER = "android.widget.EditText[text=\"Account number\"]";

}